# Generated by Django 5.2.4 on 2025-07-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_email_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
