# Generated by Django 5.2.4 on 2025-07-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='username',
        ),
    ]
