# Generated by Django 5.2.4 on 2025-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='مدل کالا')),
                ('description', models.TextField(verbose_name='اطلاعات کالا')),
                ('image', models.ImageField(upload_to='shop/', verbose_name='عکس کالا')),
                ('price', models.FloatField(verbose_name='قیمت کالا')),
                ('status', models.BooleanField(default=False, verbose_name='موجود هست یا نه')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
    ]
