# Generated by Django 5.2.4 on 2025-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='shop/', verbose_name='عکس')),
                ('price', models.FloatField(verbose_name='قیمت')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('color', models.ManyToManyField(to='shop.color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='سایز')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopList',
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='size',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
