# Generated by Django 5.2.4 on 2025-07-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_color_shopdetail_size_delete_shoplist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetail',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='shop.size'),
        ),
    ]
