# Generated by Django 5.2.4 on 2025-07-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopdetail_color_alter_shopdetail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetail',
            name='image',
            field=models.ImageField(upload_to='detail_img/', verbose_name='عکس'),
        ),
    ]
