# Generated by Django 5.2.4 on 2025-07-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_shopdetail_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='color', to='shop.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='size', to='shop.size', verbose_name='سایز'),
        ),
    ]
