# Generated by Django 5.2.4 on 2025-07-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_information_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='color', to='shop.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size', to='shop.size', verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سایز'),
        ),
    ]
