# Generated by Django 5.2.4 on 2025-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_detail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان'),
        ),
    ]
